---
# This workflow will install Python dependencies and run tests
# across operating systems, select versions of Python, and user + dev environments
# For more info see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD tests

on:
  push:
    branches: [main, dev]
    paths-ignore: # prevents workflow execution when only these types of files are modified
      - "**.md" # wildcards prevent file in any repo dir from trigering workflow
      - "**.bib"
      - "**.ya?ml" # captures both .yml and .yaml
      - "LICENSE"
      - ".gitignore"
      - "**.ipynb" # ignore Jupyter notebooks

  pull_request:
    branches: [main, dev]
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.bib"
      - "**.ya?ml"
      - "LICENSE"
      - ".gitignore"
      - "**.ipynb" # ignore Jupyter notebooks
  workflow_dispatch: # also allow manual trigger, for testing purposes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , windows-latest, macos-latest
        py-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v6

      # Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.py-version }}
          miniconda-version: "latest"  # Ensure Miniconda is installed

      # Create the conda environment
      - name: Create conda environment
        run: conda create -n timex -c conda-forge -c cmutel -c diepers brightway25 bw_temporalis dynamic_characterization matplotlib seaborn

      # Install testing dependencies from pyproject.toml
      - name: Install testing dependencies
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate timex
          pip install .[testing]

      # Verify the environment
      - name: Check conda environment
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate timex
          conda info
          conda list

      # Test with pytest
      - name: Test with pytest
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate timex
          pytest
